package labs.newrapaw.dlna.probe.core

fun buildPlaybackDiagnosticsJson(snapshot: PlaybackDiagnosticsSnapshot): String =
    buildString {
        append('{')
        appendJsonField("playbackStatus", snapshot.playbackStatus.name)
        append(',')
        appendJsonField("sessionStatus", snapshot.sessionStatus)
        append(',')
        appendJsonField("sessionStartedAtMs", snapshot.sessionStartedAtMs)
        append(',')
        appendJsonField("sourceUrl", snapshot.sourceUrl)
        append(',')
        appendJsonField("localProxyUrl", snapshot.localProxyUrl)
        append(',')
        appendJsonField("lastUpdatedAtMs", snapshot.lastUpdatedAtMs)
        append(',')
        appendJsonField("upstreamMode", snapshot.upstreamMode.name)
        append(',')
        appendJsonField("activeProxy", snapshot.activeProxy)
        append(',')
        appendJsonField("lastError", snapshot.lastError)
        append(',')
        appendJsonField("lastRequestedSegment", snapshot.lastRequestedSegment)
        append(',')
        appendJsonField("lastSucceededSegment", snapshot.lastSucceededSegment)
        append(',')
        appendJsonField("lastFailedSegment", snapshot.lastFailedSegment)
        append(',')
        appendJsonField("consecutiveFailures", snapshot.consecutiveFailures)
        append(',')
        appendJsonField("recentSegmentSamples", buildRecentSegmentSamplesJson(snapshot), isRawJson = true)
        append(',')
        appendJsonField("prefetchConcurrency", snapshot.prefetchConcurrency)
        append(',')
        appendJsonField("pendingPrefetchCount", snapshot.pendingPrefetchCount)
        append(',')
        appendJsonField("currentLoadingAssetId", snapshot.currentLoadingAssetId)
        append(',')
        appendJsonField("currentLoadingAssetKind", snapshot.currentLoadingAssetKind)
        append(',')
        appendJsonField("currentLoadingTrackId", snapshot.currentLoadingTrackId)
        append(',')
        appendJsonField("currentLoadingSource", snapshot.currentLoadingSource)
        append(',')
        appendJsonField("slotStates", buildSlotStatesJson(snapshot), isRawJson = true)
        append(',')
        appendJsonField("assetDiagnostics", buildAssetDiagnosticsJson(snapshot), isRawJson = true)
        append(',')
        appendJsonField("currentPlaybackSlotIndex", snapshot.currentPlaybackSlotIndex)
        append(',')
        appendJsonField("currentPlaybackSlotReady", snapshot.currentPlaybackSlotReady)
        append(',')
        appendJsonField("bufferedSlotIndex", snapshot.bufferedSlotIndex)
        append(',')
        appendJsonField("startupGatePhase", snapshot.startupGatePhase)
        append(',')
        appendJsonField("startupGateReady", snapshot.startupGateReady)
        append(',')
        appendJsonField("startupGateDetail", snapshot.startupGateDetail)
        append(',')
        appendJsonField("currentStallReason", snapshot.currentStallReason)
        append(',')
        appendJsonField("playerPositionMs", snapshot.playerPositionMs)
        append(',')
        appendJsonField("playerBufferedPositionMs", snapshot.playerBufferedPositionMs)
        append(',')
        appendJsonField("playerIsLoading", snapshot.playerIsLoading)
        append(',')
        appendJsonField("continuousReadySlotCount", snapshot.continuousReadySlotCount)
        append(',')
        appendJsonField("continuousReadySlotDurationMs", snapshot.continuousReadySlotDurationMs)
        append(',')
        appendJsonField("sessionReadyAssetCount", snapshot.sessionReadyAssetCount)
        append(',')
        appendJsonField("sessionTotalAssetCount", snapshot.sessionTotalAssetCount)
        append(',')
        appendJsonField("sessionReadyBytes", snapshot.sessionReadyBytes)
        append(',')
        appendJsonField("inFlightCount", snapshot.inFlightCount)
        append(',')
        appendJsonField("directWinCount", snapshot.directWinCount)
        append(',')
        appendJsonField("proxyWinCount", snapshot.proxyWinCount)
        append(',')
        appendJsonField("directAverageElapsedMs", snapshot.directAverageElapsedMs)
        append(',')
        appendJsonField("proxyAverageElapsedMs", snapshot.proxyAverageElapsedMs)
        append(',')
        appendJsonField("lastFiveAverageElapsedMs", snapshot.lastFiveAverageElapsedMs)
        append(',')
        appendJsonField("lastFiveFailureCount", snapshot.lastFiveFailureCount)
        append(',')
        appendJsonField("lastTwentyAverageElapsedMs", snapshot.lastTwentyAverageElapsedMs)
        append(',')
        appendJsonField("lastTwentyFailureCount", snapshot.lastTwentyFailureCount)
        append(',')
        appendJsonField("severity", snapshot.severity.name)
        append(',')
        appendJsonField("isStale", snapshot.isStale)
        append(',')
        appendJsonField("insights", buildInsightsJson(snapshot), isRawJson = true)
        append(',')
        appendJsonField("primaryBottleneck", buildPrimaryBottleneckJson(snapshot), isRawJson = true)
        append(',')
        appendJsonField("timeoutCount", snapshot.timeoutCount)
        append(',')
        appendJsonField("fallbackCount", snapshot.fallbackCount)
        append(',')
        appendJsonField("lastFallbackReason", snapshot.lastFallbackReason)
        append('}')
    }
