package labs.newrapaw.dlna.probe.core

import labs.newrapaw.dlna.probe.core.session.SessionAssetKind
import labs.newrapaw.dlna.probe.core.session.SessionAssetState

enum class PlaybackDiagnosticsStatus {
    IDLE,
    BUFFERING,
    PLAYING,
    PAUSED,
    STOPPED,
    FAILED,
}

enum class DiagnosticsSeverity {
    OK,
    WARN,
    CRITICAL,
}

enum class SlotDiagnosticsState {
    NOT_READY,
    READY,
    PLAYING,
    BLOCKED,
    DEGRADED,
}

data class SegmentSample(
    val url: String,
    val source: String,
    val elapsedMs: Long,
    val success: Boolean,
    val reason: String? = null,
)

data class SlotDiagnosticsItem(
    val slotIndex: Int,
    val startMs: Long,
    val endMs: Long,
    val state: SlotDiagnosticsState,
    val videoReady: Boolean,
    val audioReady: Boolean,
    val subtitleReady: Boolean,
    val blockedAssetKinds: List<SessionAssetKind>,
    val degradedAssetKinds: List<SessionAssetKind>,
    val videoAssetIdRef: String? = null,
    val audioAssetIdRefs: List<String> = emptyList(),
    val subtitleAssetIdRefs: List<String> = emptyList(),
    val prerequisiteAssetIdRefs: List<String> = emptyList(),
)

data class AssetDiagnosticsItem(
    val assetId: String,
    val kind: SessionAssetKind,
    val trackId: String?,
    val state: SessionAssetState,
    val localReady: Boolean,
    val sizeBytes: Long?,
    val lastElapsedMs: Long?,
    val lastSource: String?,
    val retryCount: Int,
    val failureReason: String?,
)

data class DiagnosticsInsight(
    val code: String,
    val message: String,
    val detail: String? = null,
)

data class PlaybackDiagnosticsSnapshot(
    val playbackStatus: PlaybackDiagnosticsStatus,
    val sessionStatus: String?,
    val sessionStartedAtMs: Long?,
    val sourceUrl: String,
    val localProxyUrl: String,
    val lastUpdatedAtMs: Long?,
    val upstreamMode: UpstreamMode,
    val activeProxy: String?,
    val lastError: String?,
    val lastRequestedSegment: String?,
    val lastSucceededSegment: String?,
    val lastFailedSegment: String?,
    val consecutiveFailures: Int,
    val recentSegmentSamples: List<SegmentSample>,
    val prefetchConcurrency: Int,
    val pendingPrefetchCount: Int,
    val inFlightCount: Int,
    val currentLoadingAssetId: String? = null,
    val currentLoadingAssetKind: String? = null,
    val currentLoadingTrackId: String? = null,
    val currentLoadingSource: String? = null,
    val slotStates: List<SlotDiagnosticsItem> = emptyList(),
    val assetDiagnostics: List<AssetDiagnosticsItem> = emptyList(),
    val currentPlaybackSlotIndex: Int? = null,
    val currentPlaybackSlotReady: Boolean? = null,
    val bufferedSlotIndex: Int? = null,
    val startupGatePhase: String? = null,
    val startupGateReady: Boolean? = null,
    val startupGateDetail: String? = null,
    val currentStallReason: String? = null,
    val playerPositionMs: Long?,
    val playerBufferedPositionMs: Long?,
    val playerIsLoading: Boolean?,
    val continuousReadySlotCount: Int = 0,
    val continuousReadySlotDurationMs: Long = 0L,
    val sessionReadyAssetCount: Int,
    val sessionTotalAssetCount: Int,
    val sessionReadyBytes: Long,
    val directWinCount: Int,
    val proxyWinCount: Int,
    val directAverageElapsedMs: Long?,
    val proxyAverageElapsedMs: Long?,
    val lastFiveAverageElapsedMs: Long?,
    val lastFiveFailureCount: Int,
    val lastTwentyAverageElapsedMs: Long?,
    val lastTwentyFailureCount: Int,
    val severity: DiagnosticsSeverity,
    val isStale: Boolean,
    val insights: List<DiagnosticsInsight>,
    val primaryBottleneck: DiagnosticsInsight?,
    val timeoutCount: Int,
    val fallbackCount: Int,
    val lastFallbackReason: String?,
) {
    companion object {
        fun empty(): PlaybackDiagnosticsSnapshot = PlaybackDiagnosticsSnapshot(
            playbackStatus = PlaybackDiagnosticsStatus.IDLE,
            sessionStatus = null,
            sessionStartedAtMs = null,
            sourceUrl = "",
            localProxyUrl = "",
            lastUpdatedAtMs = null,
            upstreamMode = UpstreamMode.PROXY_ONLY,
            activeProxy = null,
            lastError = null,
            lastRequestedSegment = null,
            lastSucceededSegment = null,
            lastFailedSegment = null,
            consecutiveFailures = 0,
            recentSegmentSamples = emptyList(),
            prefetchConcurrency = ProxySettingsState.DEFAULT_PREFETCH_CONCURRENCY,
            pendingPrefetchCount = 0,
            inFlightCount = 0,
            currentLoadingAssetId = null,
            currentLoadingAssetKind = null,
            currentLoadingTrackId = null,
            currentLoadingSource = null,
            slotStates = emptyList(),
            assetDiagnostics = emptyList(),
            currentPlaybackSlotIndex = null,
            currentPlaybackSlotReady = null,
            bufferedSlotIndex = null,
            startupGatePhase = null,
            startupGateReady = null,
            startupGateDetail = null,
            currentStallReason = null,
            playerPositionMs = null,
            playerBufferedPositionMs = null,
            playerIsLoading = null,
            continuousReadySlotCount = 0,
            continuousReadySlotDurationMs = 0L,
            sessionReadyAssetCount = 0,
            sessionTotalAssetCount = 0,
            sessionReadyBytes = 0L,
            directWinCount = 0,
            proxyWinCount = 0,
            directAverageElapsedMs = null,
            proxyAverageElapsedMs = null,
            lastFiveAverageElapsedMs = null,
            lastFiveFailureCount = 0,
            lastTwentyAverageElapsedMs = null,
            lastTwentyFailureCount = 0,
            severity = DiagnosticsSeverity.OK,
            isStale = false,
            insights = emptyList(),
            primaryBottleneck = null,
            timeoutCount = 0,
            fallbackCount = 0,
            lastFallbackReason = null,
        )
    }
}
